force-app/main/default/objects/Favorite__c/Favorite__c.object-meta.xml
<CustomObject>
    <label>Favorite</label>
    <nameField>
        <displayFormat>Fav-{0000}</displayFormat>
        <label>Favorite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Favorite__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Design_Number__c.field-meta.xml
<CustomField>
    <fullName>Design_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Design_Number__c.field-meta.xml
<CustomField>
    <fullName>Design_Number__c</fullName>
    <label>Design Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Design_Title__c.field-meta.xml
<CustomField>
    <fullName>Design_Title__c</fullName>
    <label>Design Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Main_Image_Id__c.field-meta.xml
<CustomField>
    <fullName>Main_Image_Id__c</fullName>
    <inlineHelpText>Paste the Id of the image that will be displayed on Catalog</inlineHelpText>
    <label>Main Image Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Multiple_Image_Id__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Image_Id__c</fullName>
    <inlineHelpText>Paste Ids of Images that will be displayed on Carousal</inlineHelpText>
    <label>Multiple Image Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MainCatalogController_Test.cls
@IsTest
public class MainCatalogController_Test {
    static testMethod void testCase1(){
        Lead ld = new Lead();
        ld.FirstName = 'Test';
        ld.LastName = 'LastName';
        ld.Company = 'None';
        insert ld;
        
        COntact c =  new Contact();
        c.LastName = 'Test';
        insert c;
        
        Product2 p = new Product2();
        p.Description='Test Product Entry For Product';
        p.productCode = 'P-123';
        p.isActive = true;
        p.Name = 'Test';
        p.Design_Number__c = '1.1';
        p.Design_Title__c = 'Style';
        p.Main_Image_Id__c = '12345';
        p.Multiple_Image_Id__c = '1122';
        insert p;
        
        Product2 p2 = new Product2();
        p2.Description='Test Product Entry For Product';
        p2.productCode = 'P-123';
        p2.isActive = true;
        p2.Name = 'Test2';
        p2.Design_Number__c = '1.1';
        p2.Design_Title__c = 'Style';
        p2.Main_Image_Id__c = '12345';
        p2.Multiple_Image_Id__c = '1122';
        insert p2;
        
        // insert pricebook entry for the product
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = Test.getStandardPricebookId();
        standardPrice.Product2Id = p.Id;
        standardPrice.UnitPrice = 100;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        //insert standardPrice ;      
        
        Favorite__c fv = new Favorite__c();
        fv.Lead__c = ld.Id;
        fv.Product__c = p.Id;
        insert fv;
        
        Favorite__c fv2 = new Favorite__c();
        fv2.Contact__c = c.Id;
        fv2.Product__c = p.Id;
        insert fv2;
        //MainCatalogController.getFilterType();
        MainCatalogController.queryFavProduct(ld.Id);
        MainCatalogController.queryFav(ld.Id);
        MainCatalogController.queryFav(c.Id);
        MainCatalogController.queryFavourites(ld.Id);
        MainCatalogController.queryFavourites(c.Id);
        MainCatalogController.prepareFavProduct(p,true);
        MainCatalogController.queryFavProduct2();
        List<Product2> productList = new List<Product2>();
        productList.add(p);
        MainCatalogController.convertProductIntoWrapper(productList);
        Lead led = new Lead();
        led.FirstName = 'Test';
        led.LastName = 'LastName';
        led.Company = 'None';
        MainCatalogController.createLeadRecord(led);
        MainCatalogController.queryLeadRecord(led.id);
        MainCatalogController.getProductImages(p.Id);
        MainCatalogController.saveFav(p2.Id,ld.Id);
        MainCatalogController.saveFav(p2.Id,c.Id);
        MainCatalogController.saveFav(p.Id,c.Id);
        MainCatalogController.saveFav(p.Id,c.Id);
        MainCatalogController.createOpportunity(c.Id);
        MainCatalogController.createOpportunity(ld.Id);
        MainCatalogController.deleteFav(fv.Id);
    }
    
    @IsTest
    static void tesSessionIdClass(){
        Test.setMock(HttpCalloutMock.class, new SessionIdMock());
        SessionIdClass.fetchFilteredProducts();
    }
}