force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Due</fullName>
            </value>
            <value>
                <fullName>Approved By Accounts</fullName>
            </value>
            <value>
                <fullName>Approved By Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_Lost_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Lost_Date__c</fullName>
    <label>Bill / Lost Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <label>Bill No.</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lost_Value__c.field-meta.xml
<CustomField>
    <fullName>Lost_Value__c</fullName>
    <label>Lost Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Points_Type__c.field-meta.xml
<CustomField>
    <fullName>Points_Type__c</fullName>
    <label>Points Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Color Stone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Won_Value__c.field-meta.xml
<CustomField>
    <fullName>Won_Value__c</fullName>
    <label>Won Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BulkApprovalControllerTest.cls
@isTest 
public class BulkApprovalControllerTest {
    static testMethod void testBulkApprovalController() {
       Account acc = new Account(Name = 'test');
       insert acc;
       
       Opportunity opportunityToCreate = new Opportunity();
       
       // Do you recognize these fields?
       opportunityToCreate.StageName = 'Delivered';
       opportunityToCreate.CloseDate = date.today();
       opportunityToCreate.Approval_Status__c = 'Approval Due';
       opportunityToCreate.Bill_Lost_Date__c = date.today();
       opportunityToCreate.AccountId = acc.Id;
       opportunityToCreate.Bill_No__c = 'test';
       opportunityToCreate.Lost_Value__c = 22;
       opportunityToCreate.Points_Type__c = 'Gold';
       opportunityToCreate.Won_Value__c = 34;
       opportunityToCreate.Name = 'Test Opportunity Triggers';
       
       insert opportunityToCreate;
       
       BulkApprovalController cntrl = new BulkApprovalController();
       
       Set<String> tempSet = new Set<String>();
       tempSet.add(opportunityToCreate.Id);
       
       cntrl.fetch('Opportunity', tempSet);
       cntrl.piwiIds = '';
       cntrl.approveRejectRequests();
       cntrl.reassign();
       BulkApprovalController.readFieldSet('Approval_Fields', 'Opportunity');
       
       cntrl.selectedOp = '=';
       cntrl.selectedField = 'Opportunity:Name';
       cntrl.filterIndex = 0;
       cntrl.addFilter();
       cntrl.removeFilter();
       cntrl.removeAllFilter();
       cntrl.saveFilter();
       
       BulkApprovalController.ApprovalTypeWrapper w = new BulkApprovalController.ApprovalTypeWrapper(null, null, null);
       BulkApprovalController.ApprovalWrapper ww = new BulkApprovalController.ApprovalWrapper(null, null, null);
       
    }
}